In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
attrition_df = pd.read_csv('HR-Employee-Attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
# Generate our categorical variable list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()
attrition_cat

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

In [4]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [5]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

/Users/ryanandrade/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [6]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

/Users/ryanandrade/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [7]:
# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

/Users/ryanandrade/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

In [8]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 8)                 448
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 45
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6
=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

2022-05-15 16:05:29.247005: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-15 16:05:29.248480: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 10. Tune using inter_op_parallelism_threads for best performance.

In [10]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [11]:
# Train the model
fit_model = nn.fit(X_train,y_train,epochs=100)

Train on 1102 samples
Epoch 1/100
1102/1102 [==============================] - 1s 631us/sample - loss: 2096.2127 - accuracy: 0.1724
Epoch 2/100
1102/1102 [==============================] - 0s 48us/sample - loss: 1160.7146 - accuracy: 0.1724
Epoch 3/100
1102/1102 [==============================] - 0s 53us/sample - loss: 572.4597 - accuracy: 0.1724
Epoch 4/100
1102/1102 [==============================] - 0s 51us/sample - loss: 130.0653 - accuracy: 0.3194
Epoch 5/100
1102/1102 [==============================] - 0s 51us/sample - loss: 26.3801 - accuracy: 0.7123
Epoch 6/100
1102/1102 [==============================] - 0s 49us/sample - loss: 16.6997 - accuracy: 0.6897
Epoch 7/100
1102/1102 [==============================] - 0s 49us/sample - loss: 9.6427 - accuracy: 0.6788
Epoch 8/100
1102/1102 [==============================] - 0s 43us/sample - loss: 7.1454 - accuracy: 0.7142
Epoch 9/100
1102/1102 [==============================] - 0s 46us/sample - loss: 5.6220 - accuracy: 0.7250
Epoch 10/100
1102/1102 [==============================] - 0s 55us/sample - loss: 4.7695 - accuracy: 0.7169
Epoch 11/100
1102/1102 [==============================] - 0s 45us/sample - loss: 4.1797 - accuracy: 0.7196
Epoch 12/100
1102/1102 [==============================] - 0s 42us/sample - loss: 3.7418 - accuracy: 0.7223
Epoch 13/100
1102/1102 [==============================] - 0s 44us/sample - loss: 3.3539 - accuracy: 0.7314
Epoch 14/100
1102/1102 [==============================] - 0s 42us/sample - loss: 3.1115 - accuracy: 0.7232
Epoch 15/100
1102/1102 [==============================] - 0s 42us/sample - loss: 2.8061 - accuracy: 0.7332
Epoch 16/100
1102/1102 [==============================] - 0s 41us/sample - loss: 2.4927 - accuracy: 0.7269
Epoch 17/100
1102/1102 [==============================] - 0s 41us/sample - loss: 2.3690 - accuracy: 0.7305
Epoch 18/100
1102/1102 [==============================] - 0s 44us/sample - loss: 2.0899 - accuracy: 0.7260
Epoch 19/100
1102/1102 [==============================] - 0s 46us/sample - loss: 2.0212 - accuracy: 0.7314
Epoch 20/100
1102/1102 [==============================] - 0s 45us/sample - loss: 1.7944 - accuracy: 0.7296
Epoch 21/100
1102/1102 [==============================] - 0s 45us/sample - loss: 1.7003 - accuracy: 0.7350
Epoch 22/100
1102/1102 [==============================] - 0s 44us/sample - loss: 1.6159 - accuracy: 0.7241
Epoch 23/100
1102/1102 [==============================] - 0s 43us/sample - loss: 1.4600 - accuracy: 0.7323
Epoch 24/100
1102/1102 [==============================] - 0s 41us/sample - loss: 1.4744 - accuracy: 0.7296
Epoch 25/100
1102/1102 [==============================] - 0s 41us/sample - loss: 1.3346 - accuracy: 0.7387
Epoch 26/100
1102/1102 [==============================] - 0s 40us/sample - loss: 1.4159 - accuracy: 0.7278
Epoch 27/100
1102/1102 [==============================] - 0s 41us/sample - loss: 1.4387 - accuracy: 0.7250
Epoch 28/100
1102/1102 [==============================] - 0s 40us/sample - loss: 1.1871 - accuracy: 0.7287
Epoch 29/100
1102/1102 [==============================] - 0s 44us/sample - loss: 1.1688 - accuracy: 0.7241
Epoch 30/100
1102/1102 [==============================] - 0s 44us/sample - loss: 1.2400 - accuracy: 0.7368
Epoch 31/100
1102/1102 [==============================] - 0s 45us/sample - loss: 1.3152 - accuracy: 0.7069
Epoch 32/100
1102/1102 [==============================] - 0s 40us/sample - loss: 1.3033 - accuracy: 0.7432
Epoch 33/100
1102/1102 [==============================] - 0s 41us/sample - loss: 1.1039 - accuracy: 0.7305
Epoch 34/100
1102/1102 [==============================] - 0s 40us/sample - loss: 1.0496 - accuracy: 0.7450
Epoch 35/100
1102/1102 [==============================] - 0s 41us/sample - loss: 0.8942 - accuracy: 0.7486
Epoch 36/100
1102/1102 [==============================] - 0s 42us/sample - loss: 1.0249 - accuracy: 0.7359
Epoch 37/100
1102/1102 [==============================] - 0s 41us/sample - loss: 1.1564 - accuracy: 0.7260
Epoch 38/100
1102/1102 [==============================] - 0s 44us/sample - loss: 1.0601 - accuracy: 0.7359
Epoch 39/100
1102/1102 [==============================] - 0s 42us/sample - loss: 0.9023 - accuracy: 0.7377
Epoch 40/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.7977 - accuracy: 0.7468
Epoch 41/100
1102/1102 [==============================] - 0s 43us/sample - loss: 0.7890 - accuracy: 0.7332
Epoch 42/100
1102/1102 [==============================] - 0s 41us/sample - loss: 0.8085 - accuracy: 0.7604
Epoch 43/100
1102/1102 [==============================] - 0s 42us/sample - loss: 0.8074 - accuracy: 0.7405
Epoch 44/100
1102/1102 [==============================] - 0s 42us/sample - loss: 0.7276 - accuracy: 0.7468
Epoch 45/100
1102/1102 [==============================] - 0s 42us/sample - loss: 0.7506 - accuracy: 0.7632
Epoch 46/100
1102/1102 [==============================] - 0s 43us/sample - loss: 0.6877 - accuracy: 0.7523
Epoch 47/100
1102/1102 [==============================] - 0s 41us/sample - loss: 0.6693 - accuracy: 0.7604
Epoch 48/100
1102/1102 [==============================] - 0s 41us/sample - loss: 0.7323 - accuracy: 0.7668
Epoch 49/100
1102/1102 [==============================] - 0s 56us/sample - loss: 0.7821 - accuracy: 0.7505
Epoch 50/100
1102/1102 [==============================] - 0s 49us/sample - loss: 0.6652 - accuracy: 0.7604
Epoch 51/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.6594 - accuracy: 0.7650
Epoch 52/100
1102/1102 [==============================] - 0s 47us/sample - loss: 0.6849 - accuracy: 0.7613
Epoch 53/100
1102/1102 [==============================] - 0s 46us/sample - loss: 0.6710 - accuracy: 0.7632
Epoch 54/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.6424 - accuracy: 0.7759
Epoch 55/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.5867 - accuracy: 0.7840
Epoch 56/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.5155 - accuracy: 0.7904
Epoch 57/100
1102/1102 [==============================] - 0s 50us/sample - loss: 0.5731 - accuracy: 0.7913
Epoch 58/100
1102/1102 [==============================] - 0s 52us/sample - loss: 0.6493 - accuracy: 0.7740
Epoch 59/100
1102/1102 [==============================] - 0s 52us/sample - loss: 0.5482 - accuracy: 0.7849
Epoch 60/100
1102/1102 [==============================] - 0s 58us/sample - loss: 0.5297 - accuracy: 0.7995
Epoch 61/100
1102/1102 [==============================] - 0s 48us/sample - loss: 0.5818 - accuracy: 0.7904
Epoch 62/100
1102/1102 [==============================] - 0s 43us/sample - loss: 0.6849 - accuracy: 0.7677
Epoch 63/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.5939 - accuracy: 0.7804
Epoch 64/100
1102/1102 [==============================] - 0s 42us/sample - loss: 0.5711 - accuracy: 0.7940
Epoch 65/100
1102/1102 [==============================] - 0s 41us/sample - loss: 0.5859 - accuracy: 0.7849
Epoch 66/100
1102/1102 [==============================] - 0s 41us/sample - loss: 0.6300 - accuracy: 0.7659
Epoch 67/100
1102/1102 [==============================] - 0s 43us/sample - loss: 0.6195 - accuracy: 0.7786
Epoch 68/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.6506 - accuracy: 0.7858
Epoch 69/100
1102/1102 [==============================] - 0s 45us/sample - loss: 0.7346 - accuracy: 0.7740
Epoch 70/100
1102/1102 [==============================] - 0s 49us/sample - loss: 0.6926 - accuracy: 0.7750
Epoch 71/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.8769 - accuracy: 0.7750
Epoch 72/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.9732 - accuracy: 0.7577
Epoch 73/100
1102/1102 [==============================] - 0s 43us/sample - loss: 0.6692 - accuracy: 0.7849
Epoch 74/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.5630 - accuracy: 0.7922
Epoch 75/100
1102/1102 [==============================] - 0s 42us/sample - loss: 0.5912 - accuracy: 0.7976
Epoch 76/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.5043 - accuracy: 0.8058
Epoch 77/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.4756 - accuracy: 0.7995
Epoch 78/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.6976 - accuracy: 0.7786
Epoch 79/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.8382 - accuracy: 0.7432
Epoch 80/100
1102/1102 [==============================] - 0s 44us/sample - loss: 0.7016 - accuracy: 0.7750
Epoch 81/100
1102/1102 [==============================] - 0s 43us/sample - loss: 0.5992 - accuracy: 0.7795
Epoch 82/100
1102/1102 [==============================] - 0s 43us/sample - loss: 0.5996 - accuracy: 0.7840
Epoch 83/100
1102/1102 [==============================] - 0s 42us/sample - loss: 0.5130 - accuracy: 0.7985
Epoch 84/100
1102/1102 [==============================] - 0s 42us/sample - loss: 0.4459 - accuracy: 0.8285
Epoch 85/100
1102/1102 [==============================] - 0s 42us/sample - loss: 0.4739 - accuracy: 0.8203
Epoch 86/100
1102/1102 [==============================] - 0s 43us/sample - loss: 0.5017 - accuracy: 0.7985
Epoch 87/100
1102/1102 [==============================] - 0s 41us/sample - loss: 0.5122 - accuracy: 0.8103
Epoch 88/100
1102/1102 [==============================] - 0s 40us/sample - loss: 0.5341 - accuracy: 0.7967
Epoch 89/100
1102/1102 [==============================] - 0s 41us/sample - loss: 0.6575 - accuracy: 0.7895
Epoch 90/100
1102/1102 [==============================] - 0s 40us/sample - loss: 0.9919 - accuracy: 0.7495
Epoch 91/100
1102/1102 [==============================] - 0s 40us/sample - loss: 0.5977 - accuracy: 0.7931
Epoch 92/100
1102/1102 [==============================] - 0s 40us/sample - loss: 0.6049 - accuracy: 0.7904
Epoch 93/100
1102/1102 [==============================] - 0s 41us/sample - loss: 0.8060 - accuracy: 0.7704
Epoch 94/100
1102/1102 [==============================] - 0s 40us/sample - loss: 0.4334 - accuracy: 0.8348
Epoch 95/100
1102/1102 [==============================] - 0s 40us/sample - loss: 0.5234 - accuracy: 0.8122
Epoch 96/100
1102/1102 [==============================] - 0s 43us/sample - loss: 0.7358 - accuracy: 0.7895
Epoch 97/100
1102/1102 [==============================] - 0s 43us/sample - loss: 0.8281 - accuracy: 0.7722
Epoch 98/100
1102/1102 [==============================] - 0s 41us/sample - loss: 0.4554 - accuracy: 0.8212
Epoch 99/100
1102/1102 [==============================] - 0s 39us/sample - loss: 0.4492 - accuracy: 0.8376
Epoch 100/100
1102/1102 [==============================] - 0s 40us/sample - loss: 0.4930 - accuracy: 0.8167

In [12]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

368/1 - 0s - loss: 0.4087 - accuracy: 0.8723
Loss: 0.6458943758321845, Accuracy: 0.8722826242446899